name: "Feature Request"
about: "Submit your feature request"
labels: "Enhancement"
# assignees: []
# projects: ""

body:
  - type: textarea
    id: feature_concern
    attributes:
      label: concern
      description: "Describe the problem or concept which the feature does address"..
      placeholder: "Describe the concern here"
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: feature
      description: "Describe the feature as it address the concern or addressable" concept(s)
      placeholder: "Describe the feature here"
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: email
      description: "Enter your email address if you are okay with us contacting you for clarification on your feedback.
      placeholder: "Your email address"
